blueprints/menu.py
from flask import Blueprint
from flask import Flask,request,render_template,session,redirect,url_for,jsonify   #g 可以存储全局变量
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import text
from redis import Redis
from exts import db,mail,xtredis
from models.table import User, Resume, Position, Comment, Admin
import hashlib
import json
from models.forms import RegisterForm,LoginForm,ForgotForm
from models.function import get_total_pages, redis_search_positions
import os
import time

bp = Blueprint('menu',__name__,url_prefix="/")

@bp.route('/login',methods=['GET','POST'])
def login():
    if request.method=='GET':
        return render_template('login.html')
    if request.method=='POST':
        pass
    
@bp.route('/login_action',methods=['GET','POST'])
def login_action():
    if request.method == 'GET':
        pass
    else:
        type = request.form.get('type')
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            if type == 'user':
                get_user = User.query.filter_by(email=email).first()
                if get_user is not None:
                    session['user_id'] = get_user.id
                    session['type'] = 'user'
                    password = hashlib.sha256(password.encode('utf-8')).hexdigest()
                    print(password)
                    if(get_user.password == password):
                        print(1)
                        return jsonify({'status':'success', 'message':''})
                        
            else:
                print('admin')
                get_admin = Admin.query.filter_by(email=email).first()
                if get_admin is not None:
                    session['user_id'] = get_admin.id
                    session['type'] = 'admin'
                    password = hashlib.sha256(password.encode('utf-8')).hexdigest()
                    if(get_admin.password == password):
                        return jsonify({'status': 'success', 'message':''})
        return jsonify({'status':'', 'message':'账号或密码错误'})

@bp.route('/register',methods=['GET','POST'])
def register():
    if request.method == 'GET':
        return render_template('register.html')
    else:
        pass
        

@bp.route('/register_action',methods=['GET','POST'])
def register_action():
    if request.method == 'GET':
        pass
    else:
        type = request.form.get('type')
        form = RegisterForm(request.form)
        print(form.username.data)
        if form.validate():
            email = form.email.data
            username = form.username.data
            print(username)
            password = form.password.data
            if type == 'user':
                user = User(email=email,username=username,password=hashlib.sha256(password.encode('utf-8')).hexdigest())
                # 创建 resume 对象并关联到 User
                resume = Resume(name ='',
                            age = 0,
                            expect_position = '',
                            gender = '',
                            marriage = '',
                            phone = '',
                            expect_salary = 0,
                            email = '',
                            expect_address = '',
                            education = '',
                            experience = '',
                            abilities = '',
                            about_me = '',
                            filepath = '')
                user.resume.append(resume)
                # 提交
                db.session.add(user)
                db.session.commit()
                # 创建文件夹
                if not os.path.exists('data/pictures/user/'+str(user.id)):  
                    os.makedirs('data/pictures/user/'+str(user.id))  
                if not os.path.exists('data/resumes/'+str(user.id)):  
                    os.makedirs('data/resumes/'+str(user.id))  
                
                return jsonify({'status': 'success'})
            else: #type == 'admin'
                admin = Admin(email=email,username=username,password=hashlib.sha256(password.encode('utf-8')).hexdigest())
                db.session.add(admin)
                db.session.commit()
                if not os.path.exists('data/pictures/admin/'+str(admin.id)):  
                    os.makedirs('data/pictures/admin/'+str(admin.id))  
                return jsonify({'status': 'success'})
        else:
            for field, errors in form.errors.items():  
                # errors 是一个列表，包含该字段的所有错误消息  
                if errors:  
                #     # 打印第一个错误消息  
                    error = errors[0]
                    print(f"{field} 的第一个错误是: {errors[0]}")  
                    break
                print(error)
            return jsonify({'status': '','message':error})
        
@bp.route('/forgot_password',methods=['GET','POST'])
def forgot_password():
    if request.method == 'GET':
        return render_template('forgot_password.html')
    else:
        form = ForgotForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            if User.query.filter_by(email=email).first():
                get_user = User.query.filter_by(email=email).first()
                get_user.password = hashlib.sha256(password.encode('utf-8')).hexdigest()
            elif Admin.query.filter_by(email=email).first():
                get_user = Admin.query.filter_by(email=email).first()
                get_user.password = hashlib.sha256(password.encode('utf-8')).hexdigest()
            db.session.commit()
            session.clear()
            return redirect(url_for('menu.login'))
        else:
            for field, errors in form.errors.items():  
                # errors 是一个列表，包含该字段的所有错误消息  
                if errors:  
                #     # 打印第一个错误消息  
                    error = errors[0]
                    print(f"{field} 的第一个错误是: {errors[0]}")  
                    break
                print(error)
            return render_template('forgot_password.html',error=error)

@bp.route('/',methods=['GET','POST'])
def menu():
    if request.method == 'POST':
        keyword = '前端'
        get_user = User.query.filter_by(id=session['user_id']).first()
        # results = Position.query.filter_by(Position)
        results = redis_search_positions(keyword,Position)
        results_per_page = 6  # 每页显示6条结果  
        page = int(request.form.get('page', 1))  # 获取当前页码，默认为1 
        page_results, total_pages = get_total_pages(results,results_per_page,page)
        time.sleep(4)
        return render_template('index.html',user=get_user,results=page_results,total_pages=total_pages,page=page,tj=1) 
    if request.method == 'GET':
        keyword = request.args.get('keyword')
        if keyword==None:
            keyword=''
        results = redis_search_positions(keyword,Position)
        results_per_page = 6  # 每页显示6条结果  
        page = int(request.args.get('page', 1))  # 获取当前页码，默认为1 
        page_results, total_pages = get_total_pages(results,results_per_page,page)
        
        return render_template('index.html',results=page_results,keyword=keyword,total_pages=total_pages,page=page,tj=1)


@bp.route('/logout',methods=['GET','POST'])
def logout():
    session.clear()
    return redirect('/')

blueprints/user.py
from flask import Blueprint,url_for
from flask_mail import Message
from flask import request,render_template,session,redirect,jsonify
from exts import db,mail
from models.table import User, Resume, Position, Comment, Send_resume, Admin
from models.forms import ChangeForm
import os
import shutil
import base64
import time

# user
bp = Blueprint('user',__name__,url_prefix="/")

@bp.route('/resume',methods=['GET','POST'])
def resume():
    if request.method == 'GET':
        if session:
            user_id = session.get('user_id')
            resume = Resume.query.filter_by(user_id=user_id).first()
            resume.phone = base64.b64decode(resume.phone.encode('utf-8')).decode('utf-8')
            resume.email = base64.b64decode(resume.email.encode('utf-8')).decode('utf-8')
            print(resume.email)
            user = User.query.filter_by(id=session['user_id']).first()
            return render_template('menu/resume.html',resume=resume)
        else:
            return redirect('../login')
    else: # 'POST'
        user_id = session.get('user_id')
        user = User.query.filter_by(id=user_id).first()
        name = request.form.get('name')
        age = request.form.get('age')
        gender = request.form.get('gender')
        expect_position = request.form.get('expect_position')
        marriage = request.form.get('marriage')
        phone = request.form.get('phone')
        expect_salary = request.form.get('expect_salary')
        email = request.form.get('email')
        expect_address = request.form.get('expect_address')
        education = request.form.get('education')
        experience = request.form.get('experience')
        abilities = request.form.get('abilities')
        about_me = request.form.get('about_me')

        # 检查空值并设置默认值   
        if not age or not age.isdigit():  
            age = 0  
        if not expect_salary or not expect_salary.isdigit():  
            expect_salary = 0  
        
        resume = Resume.query.filter_by(user_id=user.id).first()
        
        if resume:
            resume.name = name  
            resume.age = age  
            resume.gender = gender  
            resume.expect_position = expect_position
            resume.marriage = marriage
            resume.phone = base64.b64encode(phone.encode('utf-8'))
            resume.expect_salary = expect_salary
            resume.email = base64.b64encode(email.encode('utf-8'))
            resume.expect_address = expect_address
            resume.education = education
            resume.experience = experience
            resume.abilities = abilities
            resume.about_me = about_me
        # 提交
            db.session.commit()
            resume.phone = base64.b64decode(resume.phone.encode('utf-8')).decode('utf-8')
            resume.email = base64.b64decode(resume.email.encode('utf-8')).decode('utf-8')
            return render_template('menu/resume.html',resume=resume)
        else:
            return('失败')
    
        
@bp.route('/user_info',methods=['POST','GET'])
def user_info():
    if request.method=='GET':
        return render_template('menu/user_info.html')
    else:
        pass

@bp.route('/username_action',methods=['GET','POST'])
def username_action():
    if request.method == 'GET':
        pass
    else:
        username = request.form.get('username')
        user_id = session.get('user_id')
        if session['type'] == 'user':
            user = User.query.filter_by(id=user_id).first()
        else:
            user = Admin.query.filter_by(id=user_id).first()
        form = ChangeForm(request.form)
        if form.validate():
            username = form.username.data
            user.username = username
            db.session.commit()
            return jsonify({'status':'success','username':user.username,'message':'修改用户名成功'})
        else:
            for field, errors in form.errors.items():  
                # errors 是一个列表，包含该字段的所有错误消息  
                if errors:  
                #     # 打印第一个错误消息  
                    error = errors[0]
                    print(f"{field} 的第一个错误是: {errors[0]}")  
                    break
            return jsonify({'status':'','message':error,'username':user.username})

@bp.route('/send_resume',methods=['POST','GET'])
def send_resume():
    if request.method == 'POST':
        user_id = session.get('user_id')
        position_id = request.form.get('position_id')
        resume = Resume.query.filter_by(user_id=user_id).first()
        
        if not os.path.exists(f'data/send_resumes/{position_id}/{user_id}'):
            os.mkdir(f'data/send_resumes/{position_id}/{user_id}')
        
        if resume.filepath == '' or not os.path.exists(f'data/resumes/{resume.filepath}'):
            return jsonify({'status':'','message':'请先上传简历'})
            
        filepath = f'data/send_resumes/{position_id}/' + resume.filepath
        shutil.copy(f'data/resumes/{resume.filepath}',filepath)
        
        
        
        if Send_resume.query.filter_by(user_id=user_id,position_id=position_id).first() is not None :
            send = Send_resume.query.filter_by(user_id=user_id,position_id=position_id).first()
            send.name = resume.name  
            send.age = resume.age  
            send.gender = resume.gender  
            send.expect_position = resume.expect_position
            send.marriage = resume.marriage
            send.phone = resume.phone
            send.expect_salary =resume. expect_salary
            send.email = resume.email
            send.expect_address = resume.expect_address
            send.education = resume.education
            send.experience = resume.experience
            send.abilities = resume.abilities
            send.about_me = resume.about_me
            send.filepath = resume.filepath
            send.status = 'waiting'
            
        else:
            send = Send_resume(name = resume.name,
                            age = resume.age,
                            expect_position = resume.expect_position,
                            gender = resume.gender,
                            marriage = resume.marriage,
                            phone = resume.phone,
                            expect_salary = resume.expect_salary,
                            email = resume.email,
                            expect_address = resume.expect_address,
                            education = resume.education,
                            experience = resume.experience,
                            abilities = resume.abilities,
                            about_me = resume.about_me,
                            user_id = user_id,
                            position_id = position_id,
                            filepath = resume.filepath,
                            status = 'waiting'
                            )

            db.session.add(send)
        db.session.commit()
        
    return jsonify({'status':'success','message':'投递成功'})

# 查看已投简历
@bp.route('/sended_resume',methods=['POST','GET'])
def sended_resume():
    if request.method == 'POST':
        user_id = session.get('user_id')
        pass
    else:
        user_id = session.get('user_id')
        resumes = Send_resume.query.filter_by(user_id=user_id).all()
        sended_resumes = []
        for send_resume in resumes:
            sended_resumes.append(send_resume)
        return render_template('menu/sended_resume.html',sended_resumes=sended_resumes)
    
# @bp.route('/tuijian',methods=['POST','GET'])
# def tuijian():
#     if request.method == 'GET':
#         print('get')
#         time.sleep(1)
#         return redirect(url_for('menu.menu',tuijian='True'))
#     else:
#         print('post')
#         time.sleep(3)
#         return redirect(url_for('menu.menu'))

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="stylesheet" href="{{url_for('static',filename='/bootstrap/bootstrap.4.6.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='/css/init.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='/css/index.css')}}">
    <link rel="shortcut icon" href="./static/images/web_iron.jpg">
    {%block style%} {% endblock %}
    <title>{% block title %}{% endblock %}</title>
    <style>body{zoom: 85%;}
              
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-light">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">首页<span class="sr-only">(current)</span></a>
                    </li>
                    {% if user %}
                        {% if type == 'user' %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{url_for('user.resume')}}">个人简历</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="sended_resume" href="{{url_for('user.sended_resume')}}">已投简历</a>
                            </li>
                            {% if tj == 1 %}
                                <form action='/' method='POST'>
                                    <input type='submit' class="nav-link" value='推荐岗位' >
                                </form>
                            {% endif %}
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{url_for('admin.recruit')}}" method='POST'>招聘信息</a>
                            </li>
                        {% endif %}
                    {% endif %}
                    
                </ul>
                <ul class="navbar-nav">
                    {% if user %}
                    <li class="nav-item ">
                        <label class="nav-link">{% if type=='user' %}求职者{% else %}招聘者{% endif %}</label>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{{url_for('user.user_info')}}">{{user.username}}</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{{url_for('menu.logout')}}">退出登录</a>
                    </li>
                    {% else %}
                    <li class="nav-item ">
                        <a class="nav-link" href="{{url_for('menu.login')}}">登录</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{{url_for('menu.register')}}">注册</a>
                    </li>
                    {% endif %}
                </ul>
        </div>
    </nav>
{% block body %}
{% endblock %}
</body>

</html>

templates/forgot_password.html
{% extends 'base.html' %}

{% block title %}
    更改密码
{% endblock %}
{% block style %}
<link rel='stylesheet' href='{{url_for('static',filename='/css/forget.css')}}'> 
<script src='{{url_for('static',filename='/js/jquery.min.js')}}'></script> 
{% endblock %}
{% block body %}
<body class="container2">

    <input type="checkbox" id="a12" hidden>
    <i class="indicator"></i>
    <label class="c2" for="a12"></label>
    <div id="container" class="dark">
        <div class="bg"></div>
        <div class="moon-box">
            <div class="moon"></div>
        </div>
        <div class="sun-box">
            <div class="sun"></div>
        </div>
        <div class="sea"></div>
    </div>
    
    <div class="login_container">  
        <div class="tit">forget</div>  
        <form id="loginForm" action='/forgot_password' method='POST'> 
            <div class="form-group">
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email" placeholder='邮箱' required>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <input type="text" id="code" class="form-control" name="captcha" required placeholder="验证码">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                    </div>
                </div>
            </div> 
            <div class="form-group">
                <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder='密码长度:6-20位' required>
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="password_confirm" placeholder='确认密码' required>
            </div>
            <div class="form-group">  
                <input type="submit" id="change_button" value="更改">  
            </div>  
        </form>  
        <form id="loginForm" action="/login">
            <div id="errorMessage" class="error-message"></div>  
        </form>
    </div>
    <script src='{{url_for('static',filename='/js/register.js')}}'> </script>
    <script>
        errorMessage.textContent = '{{error}}';
    </script>
</body>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}
个人主页
{% endblock %}
{% block style %}
<link rel="stylesheet" href="{{url_for('static',filename='/css/index.css')}}">
<script src='{{url_for('static',filename='/js/echats.min.js')}}'></script> 
{% endblock %}
{% block body %}
<div id="pic" style="background-color: paleturquoise; ">
    <image src="./static/images/company.png" width="400px" height="100px" ></image>
    <form action='/' method='GET'>
        <input class="search_text" type="search" placeholder="请输入需要搜索的职位" aria-label="Search" name="keyword" value={{keyword}}>
        <input class ="search_button" type="submit" value="搜索">
    </form>
</div>
<div class="sidebar">
    <ul>
        <li>
            <h4 style="display: flex; justify-content: center; align-items: center;">热门岗位</h4>
        </li>
        <li>
            <p class="side">后端开发</p>
            <span>></span>
            <div class="sidebar-mask">
                <div>
                    <label class="lab">后端开发</label>
                </div>
                <br>
                <div class="inside">
                <a class="job" href="/?keyword=java">java</a>
                <a class="job" href="/?keyword=C">C/C++</a>
                <a class="job" href="/?keyword=PHP">PHP</a>
                <a class="job" href="/?keyword=Python">Python</a><br>
                <a class="job" href="/?keyword=Golang">Golang</a>
                </div>
            </div>
        </li>
        <li>
            <p class="side">前端开发</p>
            <span>></span>
            <div class="sidebar-mask">
                <div>
                    <label class="lab">前端开发</label>
                </div>
                <br>
                <div class="inside">
                <a class="job" href="/?keyword=IOS">IOS</a>
                <a class="job" href="/?keyword=Android">Android</a>
                <a class="job" href="/?keyword=JS">JS</a>
                <a class="job" href="/?keyword=VUE">VUE</a>
                <a class="job" href="/?keyword=前端实习生">前端实习生</a>
                <a class="job" href="/?keyword=前端工程师">前端工程师</a>
                </div>
            </div>
        </li>
        <li>
            <p class="side">教育培训</p>
            <span>></span>
            <div class="sidebar-mask">
                <div>
                    <label class="lab">教育培训</label>
                </div>
                <br>
                <div class="inside">
                <a class="job" href="/?keyword=计算机老师">计算机老师</a>
                <a class="job" href="/?keyword=机器人老师">机器人教师</a>
                <a class="job" href="/?keyword=英语老师">英语老师</a>
                <a class="job" href="/?keyword=数学老师">数学老师</a>
                <a class="job" href="/?keyword=幼师">幼师</a>
                <a class="job" href="/?keyword=助教">助教</a>
                </div>
            </div>
        </li>
        <li>
            <p class="side">运维</p>
            <span>></span>
            <div class="sidebar-mask">
                <div>
                    <label class="lab">运维</label>
                </div>
                <br>
                <div class="inside">
                <a class="job" href="/?keyword=网络工程师">网络工程师</a>
                <a class="job" href="/?keyword=网络安全">网络安全</a>
                <a class="job" href="/?keyword=网络维护">网络维护</a>
                <a class="job" href="/?keyword=网路工程师">网络工程师</a>
                <a class="job" href="/?keyword=系统安全">系统安全</a>
                <a class="job" href="/?keyword=运维工程师">运维工程师</a>
                </div>
            </div>
        </li>
        <li>
            <p class="side">通信</p>
            <span>></span>
            <div class="sidebar-mask">
                <div>
                    <label class="lab">通信</label>
                </div>
                <br>
                <div class="inside">
                <a class="job" href="/?keyword=移动通信工程师">移动通信工程师</a>
                <a class="job" href="/?keyword=5G网络优化">5G网络优化</a>
                <a class="job" href="/?keyword=网络通信技术">网络通信技术</a>
                <a class="job" href="/?keyword=通信资料员">通信资料员</a>
                <a class="job" href="/?keyword=通信施工">通信施工</a>
                <a class="job" href="/?keyword=通信项目助理">通信项目助理</a>
                </div>
            </div>
            <div class="side-image">
                <img src="./static/images/advertise.png" alt="广告" class="adver">
                </div>
        </li>
    </ul>
    
    
    
</div>
<br><br>
{% if g.user and g.type=='user' %}
<div style="height: 450px;">
    <strong><h2>个人评估</h2></strong>
      <br>
    <div class="box2">
    <div id="chart" style="width: 500px; height: 400px;position: relative;left: 50px;top: 20px; background-color: rgb(206, 231, 246);border-radius: 5%;"></div>
    <script>
      var chart = echarts.init(document.getElementById('chart'));
      var option = {
        title: {
          text: '个人评估',
          x: 'center',
          textStyle: {
                    color: '#000000' // 将文本颜色设置为黑色
                }
        },
        tooltip: {},
        legend: {
          data: ['产品A']
        },
        radar: {
          indicator: [
            {name:'动手能力', max:100},
            {name:'创新能力', max:100},
            {name:'工作经验', max:100},
            {name:'人物性格', max:100},
            {name:'未来规划', max:100}
          ],
          name:
          {
            textStyle: {
                color: '#000000' 
            }
          }
        },
        areaStyle:{},
        series: [{
          type: 'radar',
          data: [
            {
              value: [80,80,60,85,60],
            },
  
          ]
        }]
      };
      chart.setOption(option);
    </script>
    </div>
</div>
<br><br><br><br><br>
{% endif %}
<div>
    <h2>推荐岗位
    </h2>
</div>
<div class="container">  
    <div class="row" style="margin-top: 20px;">  
        <div class="col"></div>  
        <div class="col-10">  
            {% if results %}  
            <ul class="position-ul">  
                {% for result in results %}  
                <li>  
                    <div class="side-position">  
                        <img class="side-position-avatar" src="data/pictures/admin/{{result.admin.filepath}}" alt="">  
                    </div>  
                    <div class="position-main">  
                        <div class="position-title"><a href="/position_detail_action?position_id={{result.id}}">{{result.position_name}}</a></div>  
                        <div class="position-content">公司: {{result.company}}<br>月薪:{{result.salary}}</div>  
                        <div class="position-detail">  
                            <span class="position-author"></span>  
                            <span class="position-time">{{result.release_time}}</span>  
                        </div>  
                    </div> 
                </li>  
                <br>
                {% endfor %}  
            </ul>  
            {% endif %}  
  
            <!-- 分页控件 -->  
            {% set page_length=6 %}

            {% if page<=3 %}
                {% set min_page=1 %}
            {% else %}
                {% set min_page = page-2 %}
            {% endif %}

            {% if min_page+page_length>total_pages %}
                {% set page_length = total_pages - min_page + 1 %}
            {% endif %}

            <div class="pagination">  

                {% if page > 1 %}  
                    <a href="?page={{page-1}}&keyword={{keyword}}" class="pagination-link">上一页</a>  
                {% endif %}  
                {% for p in range(min_page,min_page+page_length) %}  
                    {% if p == page %}  
                        <span class="pagination-link active">{{p}}</span>  
                    {% else %}  
                        <a href="?page={{p}}&keyword={{keyword}}" class="pagination-link">{{p}}</a>  
                    {% endif %}  
                {% endfor %}  
                {% if page < total_pages %}  
                    <a href="?page={{page+1}}&keyword={{keyword}}" class="pagination-link">下一页</a>  
                {% endif %}  
            </div>
        </div>  
        <div class="col"></div>  
    </div>  
</div>
{% endblock %}